SELECT
  w.EBVP_TOP_NODE,
  w.EBVP_TOP_NODE_2,
  w.EBVP_TOP_NODE_3,
  w.Q2_TO_DATE_HC,
  COALESCE(h.HIRED_BY_Q2, 0) AS HIRED_BY_Q2,
  COALESCE(o.OPEN_REQS_AFTER_Q2, 0) AS OPEN_REQS_AFTER_Q2
FROM workforce_cte AS w
LEFT JOIN hired_by_q2_cte AS h
  ON w.EBVP_TOP_NODE = h.EBVP_TOP_NODE
  AND w.EBVP_TOP_NODE_2 = h.EBVP_TOP_NODE_2
  AND w.EBVP_TOP_NODE_3 = h.EBVP_TOP_NODE_3
LEFT JOIN open_reqs_after_q2_cte AS o
  ON w.EBVP_TOP_NODE = o.EBVP_TOP_NODE
  AND w.EBVP_TOP_NODE_2 = o.EBVP_TOP_NODE_2
  AND w.EBVP_TOP_NODE_3 = o.EBVP_TOP_NODE_3
ORDER BY w.EBVP_TOP_NODE, w.EBVP_TOP_NODE_2, w.EBVP_TOP_NODE_3;