SELECT
  EBVP_TOP_NODE,
  EBVP_NODE_2,
  REPORTS_TO_03 AS VP,
  COUNT(*) AS Q2_TO_DATE_HC
FROM GLOBAL_WORKFORCE
WHERE WEEK_NUM = 'WW1925'
GROUP BY EBVP_TOP_NODE, EBVP_NODE_2, REPORTS_TO_03
ORDER BY EBVP_TOP_NODE, EBVP_NODE_2;